---
title: "Statistical learning"
author: "Zeqi Li"
date: "2024-11-21"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(glmnet)
```

# Import data
```{r, message = FALSE}
bwt_df = read_csv("data/birthweight.csv") |> 
  janitor::clean_names() |> 
  mutate(babysex = case_match(babysex,
                              1 ~ "male",
                              2 ~ "female"),
         babysex = fct_infreq(babysex),
         frace = case_match(frace,
                            1 ~ "white",
                            2 ~ "black",
                            3 ~ "asian",
                            4 ~ "puerto rican",
                            8 ~ "other"),
         frace = fct_infreq(frace),
         mrace = case_match(mrace,
                            1 ~ "white",
                            2 ~ "black",
                            3 ~ "asian",
                            4 ~ "puerto rican",
                            8 ~ "other"),
         mrace = fct_infreq(mrace))
```

# Construct inputs for `glmnet`
```{r}
x = model.matrix(bwt ~ .,
                 data = bwt_df)[, -1]
y = bwt_df |> pull(bwt)
```

# Fit LASSO with several $\lambda$
```{r}
lambda = 10^seq(-2, 2.75, by = 0.1)

lasso_fit = glmnet(x = x,
                   y = y,
                   lambda = lambda)

lasso_cv = cv.glmnet(x = x,
                     y = y,
                     lambda = lambda)

lambda_opt = lasso_cv[["lambda.min"]]
```

# LASSO plot
```{r}
lasso_fit |> 
  broom::tidy() |> 
  filter(term != "(Intercept)") |> 
  select(term, 
         lambda,
         estimate) |> 
  complete(term, 
           lambda,
           fill = list(estimate = 0)) |> 
  ggplot(aes(x = lambda,
             y = estimate,
             group = term,
             color = term)) +
    geom_line()
```

# Look at CV results
```{r}
lasso_cv |> 
  broom::tidy() |> 
  ggplot(aes(x = log(lambda, 10),
             y = estimate)) +
  geom_point()
```

# Fit LASSO with the optimal lambda
```{r}
final_lasso_fit = glmnet(x = x,
                         y = y,
                         lambda = lambda_opt)

final_lasso_fit |> 
  broom::tidy()
```

# Pokemon data
```{r}
pokemon_df = read_csv("data/pokemon.csv") |> 
  janitor::clean_names() |> 
  select(hp, speed)
```
## Visualize
```{r}
pokemon_df |> 
  ggplot(aes(x = hp,
             y = speed)) +
  geom_point()
```

## Fit K-means
```{r}
kmeans_fit = kmeans(x = pokemon_df,
                    centers = 3)
```

## Plot K-means results
```{r}
pokemon_df = broom::augment(kmeans_fit, pokemon_df)

pokemon_df |> 
  ggplot(aes(x = hp,
             y = speed,
             color = .cluster)) +
  geom_point()
```

